export const RESET_GAME = 'RESET_GAME'

export const SET_PLAYERS_NUMBER = 'SET_PLAYERS_NUMBER'
export const SET_QUESTIONS_NUMBER = 'SET_QUESTIONS_NUMBER'
export const SET_PRICE_MULTIPLIER = 'SET_PRICE_MULTIPLIER'

export const CREATE_PLAYER = 'CREATE_PLAYER'
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME'

export const SET_PACKAGE_TEXT = 'SET_PACKAGE_TEXT'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const SET_SUBJECT_NAMES = 'SET_SUBJECT_NAMES'
export const RESET_SUBJECTS = 'RESET_SUBJECTS'

export const SET_CURRENT_QUESTION_NUM = 'SET_CURRENT_QUESTION_NUM'
export const SET_PLAYER_ANSWER = 'SET_PLAYER_ANSWER'

export const SET_UI_GAME_WIDTH = 'SET_UI_GAME_WIDTH'

export const SAVE_STATE_TO_LOCAL_STORAGE = 'SAVE_STATE_TO_LOCAL_STORAGE'
export const LOAD_STATE_FROM_LOCAL_STORAGE = 'SAVE_STATE_TO_LOCAL_STORAGE'