export const SET_PLAYERS_NUMBER = 'SET_PLAYERS_NUMBER'
export const SET_QUESTIONS_NUMBER = 'SET_QUESTIONS_NUMBER'

export const CREATE_PLAYER = 'CREATE_PLAYER'
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME'

export const ADD_SUBJECT_BLOCK = 'ADD_SUBJECT_BLOCK'

export const SET_CURRENT_QUESTION_NUM = 'SET_CURRENT_QUESTION_NUM'